### ISSUE TITLE
Please hide archived pictures

### ISSUE THREAD

**Issue by JL327** [chtaylo2/Roku-GooglePhotos#60]
I don't want my archived pictures showing on my screensaver.  Am I doing something wrong, or is that function not available?

Thanks!

**Comment by aaronslow** [comment]
I have the same issue.

**Comment by chtaylo2** [comment]
This will be added to the backlog. It will show any photos in your account.

**Comment by chtaylo2** [comment]
Closing issue. This has been fixed in Release 1.7 (https://github.com/chtaylo2/Roku-GooglePhotos/releases/tag/1.7)  Update has been pushed to Roku for publishing.

**Comment by cssagogo** [comment]
Still seeing archived photos.  They're in an album as well.  Would that make a difference?

**Comment by tibbster** [comment]
I'm also seeing archived photos in the screensaver. These photos aren't in any albums. I'm running Release v2.1 - Build 4.364.20180303

Otherwise, it's a great product.

**Comment by rewallac** [comment]
I am also seeing archived photos in the screensaver. Is there a way to force a refresh after new photos are moved to the archive?
